---
- name: update main.cf values
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^({{ item.name }} =).*$'
    line: '{{ item.name }} = {{ item.value }}'
    insertafter: '^#{{ item.name }} ='
  when: item.value != False
  with_items:
    - { name: 'myhostname', value: '{{ postfix_myhostname }}' }
    - { name: 'mydomain', value: '{{ postfix_mydomain }}' }
    - { name: 'myorigin', value: '{{ postfix_myorigin }}' }
  notify:
    - restart postfix

- include: relayhost.yml
  when: postfix_relay_enabled == True

- include: recipient-canonical.yml
