---
- name: update main.cf values
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^({{ item.name }} =).*$'
    line: '{{ item.name }} = {{ item.value }}'
    insertafter: '^#{{ item.name }} ='
  when: item.value != False
  with_items:
    - { name: 'myhostname', value: '{{ postfix_myhostname }}' }
    - { name: 'mydomain', value: '{{ postfix_mydomain }}' }
    - { name: 'myorigin', value: '{{ postfix_myorigin }}' }
  notify:
    - restart postfix
- block:

  - name: determine SMTP password
    local_action: shell {{ role_path }}/scripts/aws-ses-smtp-password.sh {{ postfix_relay_secret_key }}
    become: no
    register: aws_ses_smtp_password
    when: postfix_relay_secret_key != '' and postfix_relay_password == ''
    changed_when: False

  - name: set postfix relay password
    set_fact: postfix_relay_password={{ aws_ses_smtp_password.stdout }}
    when: postfix_relay_secret_key != '' and postfix_relay_password == ''

  - include: postfix.yml

  when: postfix_relay_enabled == True
