---
- name: install cyrus-sasl-plain package
  package: name=cyrus-sasl-plain

- name: update main.cf relayhost
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^(relayhost =).*$'
    line: 'relayhost = [{{ postfix_relay_server }}]:{{ postfix_relay_port }}'
    insertafter: '^#relayhost ='
  notify:
    - restart postfix

- name: append smtp values to main.cf
  lineinfile:
    dest: /etc/postfix/main.cf
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }} ="
    insertafter: '^relayhost ='
  with_items:
    - { name: "smtp_sasl_auth_enable", value: "yes" }
    - { name: "smtp_sasl_security_options", value: "noanonymous" }
    - { name: "smtp_sasl_password_maps", value: "hash:/etc/postfix/sasl_passwd" }
    - { name: "smtp_use_tls", value: "yes" }
    - { name: "smtp_tls_security_level", value: "encrypt" }
    - { name: "smtp_tls_note_starttls_offer", value: "yes" }
  notify:
    - restart postfix

- name: comment out smtp_fallback_relay setting
  replace:
    dest: /etc/postfix/master.cf
    regexp: '^(  -o smtp_fallback_relay=.*)$'
    replace: '#\1'
  notify:
    - restart postfix

- name: write default credentials to /etc/postfix/sasl_passwd
  lineinfile:
    dest: /etc/postfix/sasl_passwd
    line: "[{{ postfix_relay_server }}]:{{ postfix_relay_port }} {{ postfix_relay_user }}:{{ postfix_relay_password }}"
    regexp: "^\\[{{ postfix_relay_server }}\\]:{{ postfix_relay_port }}"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0600
  register: postfix_passwd_add
  notify:
    - restart postfix

- block:

  - name: append relayhost_map values to main.cf
    lineinfile:
      dest: /etc/postfix/main.cf
      line: "{{ item.name }} = {{ item.value }}"
      regexp: "^{{ item.name }} ="
      insertafter: '^relayhost ='
    with_items:
      - { name: "sender_dependent_relayhost_maps", value: "hash:/etc/postfix/relayhost_map" }
      - { name: "smtp_sender_dependent_authentication", value: "yes" }
    notify:
      - restart postfix

  - name: add each relayhost map to sasl_passwd file
    lineinfile:
      dest: /etc/postfix/sasl_passwd
      state: present
      line: "{{ item.domain }} {{ item.user | default(postfix_relay_user) }}:{{ item.password | default(postfix_relay_password) }}"
      insertbefore: "^\\[{{ postfix_relay_server }}\\]"
    with_items: "{{ postfix_relayhost_maps }}"
    notify:
      - restart postfix

  - name: add each relayhost map to relayhost_map file
    lineinfile:
      dest: /etc/postfix/relayhost_map
      state: present
      line: "{{ item.domain }} [{{ item.server | default(postfix_relay_server) }}]:{{ item.port | default(postfix_relay_port) }}"
      regexp: "^{{ item.domain }} "
      create: yes
      owner: root
      group: root
      mode: 0600
    with_items: "{{ postfix_relayhost_maps }}"
    register: postfix_relayhost_maps_update

  - name: run postmap command for virtual aliases
    command: postmap /etc/postfix/relayhost_map
    when: postfix_relayhost_maps_update.changed

  when: postfix_relayhost_maps and postfix_relayhost_maps|length > 0

- name: create hashmap database file containing SMTP credentials
  command: postmap hash:/etc/postfix/sasl_passwd
  when: postfix_passwd_add.changed
  register: postfix_hashmap_database

- name: lookup current postfix CA certificate value
  command: postconf -h 'smtp_tls_CAfile'
  register: postconf_smtp_tls_cafile
  changed_when: postconf_smtp_tls_cafile.stdout != "/etc/ssl/certs/ca-bundle.crt"

- name: tell Postfix where to find the CA certificate
  command: postconf -e 'smtp_tls_CAfile=/etc/ssl/certs/ca-bundle.crt'
  when: postconf_smtp_tls_cafile.changed
  notify:
    - restart postfix

- block:

  - name: insert virtual_alias_maps option into /etc/postfix/main.cf
    blockinfile:
      dest: /etc/postfix/main.cf
      block: |
        # Optional lookup tables that alias specific mail addresses or domains
        # to other local or remote address.
        #
        virtual_alias_maps = hash:/etc/postfix/virtual
      marker: "# {mark} ANSIBLE MANAGED BLOCK (virtual_alias_maps)"
    notify:
      - restart postfix

  - name: add address aliases to /etc/postfix/virtual
    blockinfile:
      dest: /etc/postfix/virtual
      block: |
        {{ item.address }} {{ item.alias }}
      marker: "# {mark} ANSIBLE MANAGED BLOCK ({{ item.address }})"
    with_items: '{{ postfix_virtual_alias_maps }}'
    register: postfix_virtual_alias_maps_update
    notify:
      - restart postfix

  - name: run postmap command for virtual aliases
    command: postmap /etc/postfix/virtual
    when: postfix_virtual_alias_maps_update.changed

  when: postfix_virtual_alias_maps and postfix_virtual_alias_maps|length > 0
